### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by InvertedCreeper** [amosborne/dorfperfekt#5]
Hi! I really like the look of this and would love to play it! There's just one problem though. I can't seem to install it. I have Python and PIP working, but whenever I try to install it it just says this:

ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >=3.9,<3.11; 0.2.0 Requires-Python >=3.9,<3.11; 0.2.1 Requires-Python >=3.9,<3.11
ERROR: Could not find a version that satisfies the requirement dorfperfekt (from versions: none)
ERROR: No matching distribution found for dorfperfekt

Do you know how to fix this?
Many thanks, Inverted

**Comment by InvertedCreeper** [comment]
3.11.1

**Comment by amosborne** [comment]
Try running `pip install dorfperfekt` from your python installation now. I've made an update to allow python 3.11.

**Comment by InvertedCreeper** [comment]
Thank you!!

**Comment by InvertedCreeper** [comment]
I tried it but I got this:

WARNING: The script f2py.exe is installed in 'C:\Users\fogor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts fonttools.exe, pyftmerge.exe, pyftsubset.exe and ttx.exe are installed in 'C:\Users\fogor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The scripts pyside6-assistant.exe, pyside6-deploy.exe, pyside6-designer.exe, pyside6-genpyi.exe, pyside6-linguist.exe, pyside6-lrelease.exe, pyside6-lupdate.exe, pyside6-metaobjectdump.exe, pyside6-project.exe, pyside6-qml.exe, pyside6-qmlformat.exe, pyside6-qmlimportscanner.exe, pyside6-qmllint.exe, pyside6-qmlls.exe, pyside6-qmltyperegistrar.exe, pyside6-qtpy2cpp.exe, pyside6-rcc.exe and pyside6-uic.exe are installed in 'C:\Users\fogor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  WARNING: The script dorfperfekt.exe is installed in 'C:\Users\fogor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

I still tried to run the command but it didn't work...

**Comment by amosborne** [comment]
This is an issue with your Python installation. Your Windows `Path` environment variable needs to include the Python `Scripts` directory. From your comment that would appear to be `C:\Users\fogor\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\Scripts`.

**Comment by InvertedCreeper** [comment]
What exactly do I need to do to fix the issue?

**Comment by amosborne** [comment]
The directory I identified in my previous comment, add it to the Path environment variable. [Here is a guide I found on Google for how to add something to the Path.](https://www.architectryan.com/2018/03/17/add-to-the-path-on-windows-10/)

**Comment by InvertedCreeper** [comment]
OMG THANK YOU IT'S WORKING NOW YAAAAAAAAAY!!!!

**Comment by InvertedCreeper** [comment]
Hi, me again
Sorry to be a bother, but I just recently did a clear of my downloads and it seems that I accidentally uninstalled Dorfperfekt. I'm trying to run the installation command but I am met with

File "<stdin>", line 1
    pip install dorfperfekt
        ^^^^^^^
SyntaxError: invalid syntax

How do I fix this?? I'm sorry to bring this up again

**Comment by InvertedCreeper** [comment]
Oops nvm figured it out now. Sorry for wasting your time!
