### ISSUE TITLE
n00b help plz

### ISSUE THREAD

**Issue by SweeterDieter** [amosborne/dorfperfekt#6]
Hey, it's the guy from Reddit. So I downloaded Python, but when i open it and type in: pip install dorfperfekt it says  

File "<stdin>", line 1
    pip install dorfperfekt
        ^^^^^^^
SyntaxError: invalid syntax

edit: I'm on Windows, in case this matters

**Comment by SweeterDieter** [comment]
ok so I figured out how to set the path from that other closed thread and it actually worked, I feel like a hacker now. Now I just need to figure out how to actually launch whatever I just installed

**Comment by SweeterDieter** [comment]
ha, got it, just type dorfperfekt

awesome

**Comment by SweeterDieter** [comment]
now how do I import my save file?

**Comment by amosborne** [comment]
Great that you were able to figure it out! As for loading an existing game's save file.. that's a not a provided feature.

**Comment by SweeterDieter** [comment]
hahaha alright then, I guess I still learned something :D obviously I have no idea how much work it would be, but if you'd ever make it so that it can implement save files and automatically show placements for your current tile, that would be amazing! Cheers!
