### ISSUE TITLE
Please automate!

### ISSUE THREAD

**Issue by mod3r4tor** [amosborne/dorfperfekt#7]
Hi! Thank you for this! I'm a true noob on all things related to coding/modding, but I recently got addicted to Dorfromantik, and it actually inspired me to learn how to code/modify the game. It took me an hour but I learned how to install this project, and it's almost everything I need! The only thing it's missing is the link to the game so that you don't have to manually update the application every time you place a tile. That way, we can use it only when we want to check if we have the perfect tile in a 30k point game. Having to manually switch back and forth *every time* you place a tile makes it a chore to even get to 100 tiles placed. I'd really really appreciate it if you created that bridge between the game and your awesome tool. If you think it's something a very beginner enthusiast could pull off, I'd appreciate a point in the right direction and your guidance! Thanks!

Edit: Just saw the closed posts; in case it makes a difference, what I'm hoping to have in this tool is for it to update its map automatically when the player places a tile in game - it could even be like a time delay thing, like update every 10 seconds, even if it doesn't recognize when the player makes a change on the map, and it doesn't have to recognize the next piece and suggest a place for it before you ask it to.

**Comment by amosborne** [comment]
Hello, thanks for reaching out. Obviously I can appreciate the request-- if you don't have two monitors or don't wish to play the game in windowed mode such that the two applications can be seen side by side, I can see how switching between the applications would be extremely annoying.

I think what you are requesting is extremely difficult. I am not aware of any API provided by Dorfromantik in order to interact with the game; at one point I even decompiled the game source code to take a look!

**Comment by mod3r4tor** [comment]
Thank you for the reply! I ran into another issue today as I went to load a save file (generated by dorfperfekt), but it didn't want to open, and cmd kept giving me errors (did some digging, and one of the tiles is apparently saved in an invalid location and there are too many tiles to sort xD). 

I'm sad to hear about the difficulty of automation. I tried to peek into my dorfromantik savefiles and see if there was anything useful to start working on, but no luck there either. Looks like we got some folks working on this but they all run into the same problem with lack of automation. https://www.reddit.com/r/Dorfromantik/comments/12xxaya/dorfromantik_solver/
https://github.com/patrickthomashansen/dorfromantik_helper
I do get it may be too much just for a hobby, but hey, it's an interesting puzzle in itself if you ever get back to it!

**Comment by amosborne** [comment]
Please create a new issue for the save file issue-- that I will fix. This is the first I've heard of any issue there.

I'm aware of these other tools, similar to mine. I'm not aware of any of them investigating automation.

If one were to solve automation, I would suggest it be done by DLL injection. This could turn into an arms race-- if the developers cared to, they could implement anti-cheat, I would then have to work around, and so on.

Of course it could be done. I'm personally not interested in solving this. If you were able to create a Python interface to control the game by DLL injection I would be happy to integrate it, but it sounds like that might be past your experience level.
