### ISSUE TITLE
Save loading problems

### ISSUE THREAD

**Issue by InvertedCreeper** [amosborne/dorfperfekt#8]
Hi there, I've recently encountered an issue with loading my save. I'm not sure what it means, but I'll attach an image below.
![image](https://github.com/amosborne/dorfperfekt/assets/103651245/194b8dae-6d1f-424d-a3dc-88d33637db99)

**Comment by amosborne** [comment]
Hello, thanks for reaching out. Would you mind attaching your dorfperfekt save file to this issue? Its a simply plain text file and does not include any identifying information-- let me know if you have any issue locating it.

This error is raised when loading the save file. During loading, the save file reads tiles in one at time in the order they are played... apparently one of the tiles in the file is not a valid placement. Do you have any recollection of how this may have arisen? Like whether you used the "delete tile" feature in the GUI or perhaps modified the save file manually?

Given the save file it should be straightforward to locate the tile where things have gone wrong.

**Comment by InvertedCreeper** [comment]
I can't upload the file itself, but here is its contents

GGGGGG 0 0
CCCCCC 4 0
CCCCCC 0 4
CCCCCC 2 2
CCCCCC 1 3
CCCCCC 3 1
CCCCCC -1 4
CCCCCC -2 4
CCCCCC -3 4
CCCCCC -4 4
CCCCCC -4 3
CCCCCC -4 2
CCCCCC -4 1
CCCCCC -4 0
CCCCCC -3 -1
CCCCCC -2 -2
CCCCCC -1 -3
CCCCCC 0 -4
CCCCCC 1 -4
CCCCCC 2 -4
CCCCCC 3 -4
CCCCCC 4 -4
CCCCCC 4 -3
CCCCCC 4 -2
CCCCCC 4 -1
CCDGGC 1 0
GGGFFF -1 0
FFFWFW -2 0
GGGGGG 3 -3
FRRFFF 0 2
FFWRRW -1 -1
GTGTDG 2 -2
DRDDGG 1 -3
FRFGFG -2 1
GGGGFF -3 1
CCCCCC 3 -2
GGGFGG -1 1
CCCCCC 1 -1
GGFFFG 0 -1
RGGRRG -2 2
DGCCCC 0 -3
DGGRRR -1 3
WFFFWT 1 1
FFFGGD 0 1
TRTGRR 2 0
RFDGGF -2 -1
GDDDGG 2 -3
WFWGWD -3 0
GGFFFF 1 2
CCCDRF 0 3
FRFRGF -1 2
CRFGCC -1 -2
WFWWGD 0 -2
TGCCRD 1 -2
TRGGTG 2 -1
CTRTCC 3 -1
GGWTTW 3 0
GWFWRW 2 1
GGCCCG -3 3
RGGGGF -3 2
RCCGGF -2 3

I used the delete tile feature in the gui but I haven't edited the file manually at all

**Comment by amosborne** [comment]
Huh, the ordering of all these tiles is rather odd. What game mode was this?
I'm not surprised this is related to the delete function; I will take another look at it this weekend.

**Comment by InvertedCreeper** [comment]
This is creative mode

**Comment by amosborne** [comment]
I've published a fix in commit 190c4cebcadb927eded268037f9f54036bafa3f0 to PyPI that I believe should fix your file when you go to open it. Please run `pip install dorfperfekt --upgrade` to get the latest and let me know if it resolves your issue.

**Comment by InvertedCreeper** [comment]
Yes this worked thank you!
