### ISSUE TITLE
'charmap' codec can't decode byte 0x81 in position x, character maps to <undefined>

### ISSUE THREAD

**Issue by Afkwtf** [amosborne/dorfperfekt#9]
Hi! When trying to open any save file for my game, i get this error: File "C:\Users\Yair\AppData\Local\Programs\Python\Python310\lib\site-packages\dorfperfekt\__main__.py", line 343, in open
    self.tilemap = TileMap.from_file(filename)
  File "C:\Users\Yair\AppData\Local\Programs\Python\Python310\lib\site-packages\dorfperfekt\tilemap.py", line 50, in from_file
    for line in file:
  File "C:\Users\Yair\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1485: character maps to <undefined>. 

I added a try/except clause into the code and observed 100's of instances of this error ocurring. As well, I tried changed the encoding used in the open() function to UTF-8, Latin-1, etc, and none worked.

**Comment by amosborne** [comment]
Are you trying to open an actual Dorfromantik game file? This software doesn't support that at this time.

If you are trying to open a Dorfperfekt save file and it is failing, please send me the file and I will help troubleshoot.

**Comment by Afkwtf** [comment]
[Saves.zip](https://github.com/amosborne/dorfperfekt/files/15471673/Saves.zip)

Correct, I'm trying to open a .sav fale.

**Comment by amosborne** [comment]
That file appears to be a Dorfromantik game file. This software is not capable of opening those. The intent is for this software to be used independently and in parallel to the actual game.
